simplify branch switching

diff --git a/dot_bash_aliases b/dot_bash_aliases
--- a/dot_bash_aliases
+++ b/dot_bash_aliases
@@ -440,12 +440,12 @@ ytm() {
 
 # git
 
-# alias bb=gb
+# alias ga=_git_commit
 # alias gr=git_root
-alias b=_git_branch
+alias b=_git_branch_fzf
 alias cr=git_root
 alias e=v
-alias ga=_git_commit
+alias gb=_git_branch
 alias gl=git_log
 alias i=b
 alias s=_git_commit # should increasingly be done in vim
@@ -461,10 +461,10 @@ alias gCH="git show --oneline HEAD | cat; echo; read -r -p 'confirm?'; git reset
 alias gdn="git diff --no-index"                                                                 # https://stackoverflow.com/a/17433969 -- TODO: handle symlinks
 alias gdnc="git diff --color-words=. --no-index"                                                # diff by char; may be replaced with delta
 alias gig='$EDITOR $(_get_repo_root)/.gitignore'
-alias gm,='gb && gmm'
+alias gm,='_git_branch && gmm'
 alias gx='git log --author=$(git config --get user.email) --branches --format="%h%x09%S%x09%s" --pickaxe-regex -S' # TODO: colt would be nice, but then it can't be an alias anymore
 
-gdns() { gdn -U0 <(sort -u "$1") <(sort -u "$2"); }
+gdns() { gdn -U0 <(sort -u "$1") <(sort -u "$2"); } # sort lines and diff
 
 # git info {{{
 # functions that only report info
@@ -765,20 +765,28 @@ gsdel() {
 _commit_or_discard() {
 	: returns 0 if committed
 
-	# TODO: fzf better
 	committed=1
-	while read -r f; do
-		f=$(_get_repo_root)/$f
-		[[ -f $f ]] || continue
-		if
-			git commit -v --untracked-files=no "$f"
-		then
-			committed=0
-		else
-			# TODO: checkout fails if f is staged; must gA
-			git checkout -- "$f"
-		fi
-	done < /dev/stdin
+
+	# while read -r f; do
+	# 	f=$(_get_repo_root)/$f
+	# 	[[ -f $f ]] || continue
+	# 	if
+	# 		git commit -v --untracked-files=no "$f"
+	# 	then
+	# 		committed=0
+	# 	else
+	# 		# TODO: checkout fails if f is staged; must gA
+	# 		git checkout -- "$f"
+	# 	fi
+	# done < /dev/stdin
+
+	< /dev/stdin cat |
+		while read -r f; do
+			f=$(_get_repo_root)/$f
+			[[ -f $f ]] || continue
+		done |
+		xargs git commit -v --untracked-files=no # TODO: -n1?
+	git checkout -- "$(_get_repo_root)"
 
 	return "$committed"
 }
@@ -1022,97 +1030,120 @@ gpick() {
 
 # }}}
 # git branch # {{{
-gb() { # {{{
-	: switch to new branch, or existing branch
 
-	default_local_branch=$(_gmaster)
-	current_local_branch=$(_git_current_branch)
+# create new branch, basing off current branch (this is the default behaviour of switch)
+alias gbc="git switch --create"
+
+gbr() {
+	: switch to remote branch
+	git fetch
+	git branch --remotes |
+		seen |
+		# TODO: filter out branches that exist locally
+		fzf |
+		# --guess (default) switches to remote branch if found
+		xargs git switch --create
+}
+
+_git_branch() { # {{{
+	: switch to new branch, or existing branch. with no arg, switches to master
+
+	# new branches are always based off latest master; the default
+	# behaviour of git switch -c is to base off the current branch, but
+	# this is generally not useful (in the rare cases that basing off
+	# current branch is required, call gbc instead)
+
+	# regardless of the start point, it is common to be prevented from
+	# switching branches due to the presence of unstaged/uncommitted
+	# changes, which is highly disruptive:
+	#
+	# error: Your local changes to the following files would be overwritten
+	# by checkout: ... Please commit your changes or stash them before you
+	# switch branches.
+	#
+	# most unstaged changes are usually throwaway code that was never meant
+	# to be committed (and could thus be discarded with git switch
+	# --discard-changes). but some unstaged changes are wips that -do- need
+	# to be committed before switching, so we ask for every file.
+	#
+	# note that git switch --conflict brings uncommitted changes into
+	# master, causing conflict markers to appear. this is never desired
+	# (because we want to start from a clean slate), so conflicts must be
+	# resolved in the current branch, -before- the checkout
 
 	commit_unstaged_changes() {
-		# it is common to be prevented from switching branches due to
-		# the presence of uncommitted changes, which is highly
-		# disruptive.
-		#
-		# preserving currently unstaged changes in the new branch is
-		# just annoying, because these unstaged changes are usually
-		# throwaway code that was never meant to be committed. but
-		# --discard-changes is also unsafe, so ask for every file.
+
+		# we always compare the current branch to the current state of
+		# master (-before- fetch)
 
 		# presumably, ' M	' can be safely ignored?
 		# git diff-tree HEAD "$target"
 		# git diff-index "$target"
 		# git diff --numstat "$target"...HEAD
 
-		git diff-index "$1" |
+		git diff-index "$start_branch" |
 			grep -P '00000 [AM]	' |
 			cut -f2 |
 			_commit_or_discard && git push
 	}
 
+	start_branch=$(_gmaster)
+
 	if [[ $# -eq 0 ]]; then
-		if [[ $default_local_branch == "$current_local_branch" ]]; then
-			echo "Already on $default_local_branch"
+		if [[ $(_git_current_branch) == "$start_branch" ]]; then
+			echo "Already on $start_branch"
 		else
+			# relatively uncommon, and there are probably better ways to update master
 			# func retval is not propagated to parent
-			git checkout "$default_local_branch" || return 1
+			git checkout "$start_branch" || return 1
 			timeout 30 git pull
 		fi
+		return
+	fi
+
+	# if
+	# 	! git branch | grep -qPx "[ *] $target" &&
+	# 		timeout 30 git pull &&
+	# 		git branch -r | grep -q "origin/$target"
+	# then
+	# 	# note: git hook stdout cannot be suppressed
+	# 	echo "Switching to remote branch $target"
+	# 	git switch "$target" > /dev/null || return 1
+
+	# if
+	# 	commit_unstaged_changes "$start_branch" #&&
+	# 	git switch --create "$new_branch" "$start_branch" > /dev/null 2> /dev/null
+	# then
+	# 	# for some reason, newly created branches don't know
+	# 	# which repo to pull from
+	# 	git pull "$(_get_remote)" "$start_branch"
+	# else
+	# 	commit_unstaged_changes "$new_branch"
+	# 	git switch "$new_branch"
+	# fi
+
+	commit_unstaged_changes "$start_branch"
+
+	new_branch=$1
+
+	# TODO: if this is stable, this should be simple enough to port into vim
+
+	if
+		# existing local branch
+		git branch | grep -Fqw "$new_branch"
+	then
+		git switch "$new_branch"
 	else
-
-		target=$1
-
-		# generally, new branches should target master. however, this
-		# may not always be the case, so accept an optional 2nd arg to
-		# specify target branch (should be current)
-
-		# --conflict will cause conflict markers to appear in master.
-		# this is never desired, so conflicts should be resolved in the
-		# current branch (i.e. -before- the checkout)
-
-		# existing remote branch > create local branch > existing local branch
-		if
-			! git branch | grep -qPx "[ *] $target" &&
-				timeout 30 git pull &&
-				git branch -r | grep -q "origin/$target"
-		then
-			# note: git hook stdout cannot be suppressed
-			echo "Switching to remote branch $target"
-
-			# TODO: --guess?
-			git switch "$target" > /dev/null || return 1
-
-		elif
-			commit_unstaged_changes "$default_local_branch" #&&
-			git switch --create "$target" "$default_local_branch" > /dev/null 2> /dev/null
-		then
-			# for some reason, newly created branches don't know
-			# which repo to pull from
-			git pull "$(_get_remote)" "$default_local_branch"
-
-		else
-
-			# plain git switch can fail, if 'files would be
-			# overwritten by checkout'. with --conflict, switch
-			# always succeeds, but may result in conflicts which
-			# must be resolved in the new branch
-
-			commit_unstaged_changes "$target"
-			git switch "$target"
-
-			# # alternatively, revert all unstaged changes, then
-			# # switch. this is probably more fragile
-			# git switch "$branch" 2>&1 |
-			# 	grep '^\s' |
-			# 	xargs git checkout --
-
-		fi
+		# new local branch
+		git pull origin "$start_branch:$start_branch" # https://stackoverflow.com/a/16560695
+		git switch --create "$new_branch" "$start_branch"
 	fi
 
 	# check if (dev) branch is behind remote
 	# rev-list probably wouldn't be useful if we don't fetch though
 	# note: rev-list errors if branch has no remote yet
-	if [[ "$(git rev-list --left-right --count \
-		"origin/$target...HEAD" 2> /dev/null | cut -f1)" -gt 0 ]]; then
+	if (("$(git rev-list --left-right --count \
+		"origin/$new_branch...HEAD" 2> /dev/null | cut -f1)" > 0)); then
 		set -x
 		git pull
 		set +x
@@ -1120,44 +1151,52 @@ gb() { # {{{
 
 } # }}}
 
-_complete_gb() {
-	f() {
-		# shellcheck disable=SC2317
-		git branch --list "$1*" 2> /dev/null |
-			grep -Po '[a-z].+'
-	}
-	_base_completer f
-}
+# # rarely used, because for existing branches it is faster to just call b, and
+# # new branches cannot be completed anyway
+# _complete_gb() {
+# 	# shellcheck disable=SC2317
+# 	f() { git branch --list "$1*" 2> /dev/null | grep -Po '[a-z].+'; }
+# 	_base_completer f
+# }
+# # we complete the alias, not the func
+# complete -F _complete_gb gb
 
-complete -F _complete_gb gb
+_git_branch_fzf() {
+	: switch interactively to existing branch, aliased to b
+	# does not handle existing remote branch; use gbr instead
 
-_git_branch() {
-	: switch to existing branch, aliased to b
 	# https://stackoverflow.com/a/1441062
 	# --pretty=format:'%h%x09%an%x09%ad%x09%s' # no color
 
 	_in_git_repo || return
-	if [[ $(git branch | wc -l) -eq 1 ]]; then
+	if (($(git branch | wc -l) == 1)); then
 		echo "No other branches; create one with gb <branch>"
 		return
 	fi
 
 	prv_cmd=$(
+		# if branch, show log starting from master
+		# if master, the range `master..master` fails, so show entire git log
+		# TODO: branch with no commits = empty preview
 		cat <<- EOF
-			echo {} | sed -r 's/^[ *]+/$(_gmaster)../' | xargs git log --oneline --color=always | grep . ||
-				git log --oneline  --color=always {}
+			echo {} |
+				sed -r 's/^/$(_gmaster)../' |
+				xargs git log --oneline --color=always |
+				grep . ||
+			git log --oneline  --color=always {}
 		EOF
 	)
 	branch=$(git branch --sort=-committerdate |
-		fzf --preview="$prv_cmd" --preview-window='right,80%,border' --ansi |
-		sed -r 's/^[ *]+//')
+		awk '{print $NF}' |
+		fzf --preview="$prv_cmd" --preview-window='right,80%,border' --ansi)
 	[[ -z $branch ]] && return
-	gb "$branch"
+	_git_branch "$branch"
 
 }
 
 gbd() {
 	: prune local branches that no longer exist on remote -- unstaged changes will be lost!
+	# this should generally not be run automatically
 	# https://stackoverflow.com/a/46192689
 	git branch -vv |
 		grep ': gone]' |
@@ -2291,7 +2330,7 @@ topa() {
 }
 
 randalb() { # {{{
-	# generate list of random albums rated >=3 amounting to 50 gb
+	# generate list of random albums rated >=3 amounting to 50 GB
 	set -euo pipefail
 	sql=$(
 		# note: unlike select_random.sql, the ORDER BY random() is used
@@ -2320,7 +2359,7 @@ randalb() { # {{{
 	)
 
 	# size=0
-	((size = 0, max = 50 * 1024 ** 2)) # 50 gb
+	((size = 0, max = 50 * 1024 ** 2)) # 50 GB
 	db=~/disq/collection2.db
 	dirs=()
 
